<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <title>Pay and Transfer</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="../styles/style.css">
</head>
<body>
    <?php
        require 'navbar.html';
    ?>

    <div class="title-container">
        <div class="title">
            <h1 class="oswaldMedium scaling-title-text">Send money to?</h1>
        </div>
        <div class="divider"></div>
    </div>

    <div class="container-fluid">
        <ul class="list-group payee-list" id="payee-list">
            <!-- Content auto generated by payeeList.js -->
        </ul>
    </div>

    <div class="manual-spacer" style="height: 170px;"></div>

</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<script src="../scripts/payeeList.js"></script>
</html>
